services:
  - type: web
    name: emotion-music-app
    env: python
    region: oregon
    pythonVersion: "3.11.8"
    buildCommand: |
      cd emotion-service && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: |
      cd emotion-service && gunicorn emotion_service:app
    autoDeploy: true
