services:
  - type: web
    name: emotion-music-app
    env: python
    region: oregon
    plan: free
    python_version: 3.11.8
    rootDirectory: emotion-service
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn emotion_service:app
